name: Build and deploy Python app to Azure Web App - PitchMaster

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t PitchMaster:latest .

      # Tag Docker image
      - name: Tag Docker image
        run: docker tag PitchMaster:latest mmyregistry.azurecr.io/PitchMaster:latest

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: mmyregistry.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      # Push Docker image
      - name: Push Docker image
        run: docker push mmyregistry.azurecr.io/PitchMaster:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Configure Azure Web App Container
      - name: Configure Azure Web App Container
        run: |
          az webapp config container set \
            --name PitchMaster \
            --resource-group PitchMaster \
            --docker-custom-image-name mmyregistry.azurecr.io/PitchMaster:latest \
            --docker-registry-server-url https://mmyregistry.azurecr.io \
            --docker-registry-server-user ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} \
            --docker-registry-server-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      # Deploy to Azure Web App for Containers
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PitchMaster'
          images: mmyregistry.azurecr.io/PitchMaster:latest
          resource-group: 'PitchMaster'
          slot-name: 'production'
