name: Build and deploy Python app to Azure Web App - PitBuddy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pitbuddy:latest .

      - name: Tag Docker image
        run: docker tag pitbuddy:latest mmyregistry.azurecr.io/pitbuddy:latest

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myregistry.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: docker push mmyregistry.azurecr.io/pitbuddy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PitBuddy'
          images: mmyregistry.azurecr.io/pitbuddy:latest
          resource-group: 'AIBuddy'
